package com.smartcampus.notification.model;

public enum NotificationType {
    USER_REGISTERED,
    USER_ACCOUNT_CREATED,
    USER_ACCOUNT_UPDATED,
    USER_ROLE_CHANGED,
    BOOKING_CREATED,
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    ASSET_CREATED,
    ASSET_UPDATED,
    ASSET_DELETED,
    ASSET_TYPE_CREATED,
    ASSET_TYPE_UPDATED,
    ASSET_TYPE_DELETED,
    LOCATION_CREATED,
    LOCATION_UPDATED,
    LOCATION_DELETED,
    SYSTEM_INFO
}
